name: Anypoint Exchange Asset Upload

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: npm install anypoint-cli and run command
        if: |
          ${{ github.event.pull_request.merged == true }} &&
          ${{ github.event.label.name == 'publish' }}
        run: |
          npm install -g anypoint-cli@latest
          anypoint-cli --username="T_PWD }}" exchange asset upload ${{ secrets.MULESOFT_GRP_ID }}/${{ github.event.release.tag_name }}/${{ github.event.pull_request.title }} --apiVersion v1 --name ${{ github.event.repository.name }} --classifier oas api.yaml
