name: Anypoint Exchange Asset Upload

on:
  push:
    branches:
      [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: npm install anypoint-cli and run command
        if: contains(${{ github.push.head_commit.message }}, '.')
        run: |
          npm install -g anypoint-cli@latest
          echo "42133235-551d-490e-a5e1-96ca681126d8/${{ github.event.repository.name }}/${{ github.action_ref }}"
          anypoint-cli --username="${{ secrets.MULESOFT_USR }}" --password="${{ secrets.MULESOFT_PWD }}" exchange asset upload 42133235-551d-490e-a5e1-96ca681126d8/${{ github.event.repository.name }}/${{ github.push.head_commit.message }} --apiVersion v1 --name ${{ github.event.repository.name }} --classifier oas api.yaml
